version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zoohost
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    hostname: kafkahost
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.84
      KAFKA_ZOOKEEPER_CONNECT: 'zoohost:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "test-topic"
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

